# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-09 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nome', max_length=100, verbose_name='nome')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('cargo', models.CharField(max_length=100, verbose_name='cargo')),
                ('image', models.ImageField(upload_to='event', verbose_name='imagem detalhe')),
                ('proposal', models.CharField(max_length=100, verbose_name='proposta')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'candidato',
                'verbose_name_plural': 'candidatos',
            },
        ),
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=128, verbose_name='sigla')),
                ('name', models.CharField(max_length=128, verbose_name='nome')),
                ('number', models.IntegerField(verbose_name='numero')),
            ],
            options={
                'verbose_name': 'partido político',
                'verbose_name_plural': 'partidos políticos',
            },
        ),
    ]
