# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-09 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20180608_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='number',
            field=models.CharField(default=0, max_length=100, verbose_name='número'),
            preserve_default=False,
        ),
    ]
