# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-09 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_evaluate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluate',
            options={'verbose_name': 'opção de avaliação', 'verbose_name_plural': 'opção de avaliações'},
        ),
        migrations.AlterField(
            model_name='evaluate',
            name='text',
            field=models.TextField(max_length=500, verbose_name='nome'),
        ),
    ]
